// Code generated by "stringer -type=Errors -output=errors_string.go"; DO NOT EDIT.

package ratatxt

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AppKeyErrNotFound-2100]
	_ = x[AppKeyErrRequiredID-2101]
	_ = x[AppKeyErrRequiredUserID-2102]
	_ = x[AppKeyErrLimit-2103]
	_ = x[AuthErrNoAccess-2000]
	_ = x[AuthErrNotFound-2001]
	_ = x[AuthErrRequiredID-2002]
	_ = x[AuthErrRequiredUserID-2003]
	_ = x[AuthErrVerificationReqFields-2004]
	_ = x[AuthErrLoginReqFields-2005]
	_ = x[AuthErrNotUsernameUsed-2006]
	_ = x[AuthErrInvalidRefreshToken-2007]
	_ = x[AuthErrInvalidLogin-2008]
	_ = x[DeviceErrNotFound-3000]
	_ = x[DeviceErrRequiredID-3001]
	_ = x[DeviceErrRequiredUserID-3002]
	_ = x[DeviceErrRequiredFields-3003]
	_ = x[DeviceErrDupName-3004]
	_ = x[MessageErrNotFound-4000]
	_ = x[MessageErrRequiredID-4001]
	_ = x[SMSGuardErrNotFound-9000]
	_ = x[SMSGuardErrRequiredID-9001]
	_ = x[SMSGuardErrRequiredUserID-9002]
	_ = x[SMSGuardErrReqFields-9003]
	_ = x[StatsErrNotFound-6000]
	_ = x[StatsErrScopeStringRequired-6001]
	_ = x[StatsErrScopeNotParsable-6002]
	_ = x[UserErrNotFound-1000]
	_ = x[UserErrRequiredID-1001]
	_ = x[UserErrRequiredFields-1002]
	_ = x[WebhookErrNotFound-5000]
	_ = x[WebhookErrRequiredID-5001]
	_ = x[WebhookErrRequiredUserID-5002]
	_ = x[WebhookErrLimit-5003]
}

const (
	_Errors_name_0 = "UserErrNotFoundUserErrRequiredIDUserErrRequiredFields"
	_Errors_name_1 = "AuthErrNoAccessAuthErrNotFoundAuthErrRequiredIDAuthErrRequiredUserIDAuthErrVerificationReqFieldsAuthErrLoginReqFieldsAuthErrNotUsernameUsedAuthErrInvalidRefreshTokenAuthErrInvalidLogin"
	_Errors_name_2 = "AppKeyErrNotFoundAppKeyErrRequiredIDAppKeyErrRequiredUserIDAppKeyErrLimit"
	_Errors_name_3 = "DeviceErrNotFoundDeviceErrRequiredIDDeviceErrRequiredUserIDDeviceErrRequiredFieldsDeviceErrDupName"
	_Errors_name_4 = "MessageErrNotFoundMessageErrRequiredID"
	_Errors_name_5 = "WebhookErrNotFoundWebhookErrRequiredIDWebhookErrRequiredUserIDWebhookErrLimit"
	_Errors_name_6 = "StatsErrNotFoundStatsErrScopeStringRequiredStatsErrScopeNotParsable"
	_Errors_name_7 = "SMSGuardErrNotFoundSMSGuardErrRequiredIDSMSGuardErrRequiredUserIDSMSGuardErrReqFields"
)

var (
	_Errors_index_0 = [...]uint8{0, 15, 32, 53}
	_Errors_index_1 = [...]uint8{0, 15, 30, 47, 68, 96, 117, 139, 165, 184}
	_Errors_index_2 = [...]uint8{0, 17, 36, 59, 73}
	_Errors_index_3 = [...]uint8{0, 17, 36, 59, 82, 98}
	_Errors_index_4 = [...]uint8{0, 18, 38}
	_Errors_index_5 = [...]uint8{0, 18, 38, 62, 77}
	_Errors_index_6 = [...]uint8{0, 16, 43, 67}
	_Errors_index_7 = [...]uint8{0, 19, 40, 65, 85}
)

func (i Errors) String() string {
	switch {
	case 1000 <= i && i <= 1002:
		i -= 1000
		return _Errors_name_0[_Errors_index_0[i]:_Errors_index_0[i+1]]
	case 2000 <= i && i <= 2008:
		i -= 2000
		return _Errors_name_1[_Errors_index_1[i]:_Errors_index_1[i+1]]
	case 2100 <= i && i <= 2103:
		i -= 2100
		return _Errors_name_2[_Errors_index_2[i]:_Errors_index_2[i+1]]
	case 3000 <= i && i <= 3004:
		i -= 3000
		return _Errors_name_3[_Errors_index_3[i]:_Errors_index_3[i+1]]
	case 4000 <= i && i <= 4001:
		i -= 4000
		return _Errors_name_4[_Errors_index_4[i]:_Errors_index_4[i+1]]
	case 5000 <= i && i <= 5003:
		i -= 5000
		return _Errors_name_5[_Errors_index_5[i]:_Errors_index_5[i+1]]
	case 6000 <= i && i <= 6002:
		i -= 6000
		return _Errors_name_6[_Errors_index_6[i]:_Errors_index_6[i+1]]
	case 9000 <= i && i <= 9003:
		i -= 9000
		return _Errors_name_7[_Errors_index_7[i]:_Errors_index_7[i+1]]
	default:
		return "Errors(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
